[package]
name = "ente-icons"
edition.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
encoding_rs.workspace = true
ente-core.workspace = true
futures-util.workspace = true
image.workspace = true
psl.workspace = true
scraper.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt", "time"] }
url.workspace = true

[dev-dependencies]
mockito.workspace = true
tokio = { workspace = true, features = ["macros"] }

[lints]
workspace = true
