name: ente_crypto_dart_adapter
description: CryptoApi implementation backed by ente_crypto_dart.

resolution: workspace
environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  ente_crypto_api:
    path: ../ente_crypto_api
  ente_crypto_dart:
    git:
      url: https://github.com/ente/ente_crypto_dart.git
      ref: b3f17aac6973b630aff663e4d9f7c6ee92334a62
  meta: 1.18.3

dev_dependencies:
  flutter_lints: 6.0.0
  flutter_test:
    sdk: flutter
