[package]
name = "ente-core"
edition.workspace = true

[dependencies]
argon2 = { version = "0.6.0", default-features = false, features = ["alloc"] }
base64 = { version = "0.23.1", default-features = false, features = ["std"] }
blake2b_simd = "1.0.5"
crypto_secretbox = { version = "0.1.0", default-features = false, features = ["alloc", "salsa20"] }
crypto_secretstream = "=0.2.0"
getrandom.workspace = true
hpke = { version = "0.14.1", default-features = false, features = ["alloc", "chacha", "getrandom", "mlkem", "x25519"] }
log.workspace = true
md-5.workspace = true
rand_core_06 = { package = "rand_core", version = "0.6.0", features = ["getrandom"] }
reqwest = { workspace = true, features = ["http2", "charset", "system-proxy", "json", "rustls-tls-native-roots", "rustls-tls-webpki-roots"] }
salsa20 = "0.11.0"
serde.workspace = true
serde_json.workspace = true
subtle.workspace = true
thiserror.workspace = true
x25519-dalek = { version = "3.0.0", features = ["static_secrets"] }
zeroize.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
bytes = "1.12.1"
futures-core = "0.3.34"
reqwest = { workspace = true, features = ["stream"] }
tokio = { workspace = true, features = ["time"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
gloo-timers = { version = "0.4.0", features = ["futures"] }

[dev-dependencies]
mockito.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }

[lints]
workspace = true
