package repo

import (
	"database/sql"
	"os"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestFriendNotificationsFollowRequestLifecycle(t *testing.T) {
	module := newSpaceTestModule(t)
	ctx := t.Context()
	alice, bob := notificationTestSpaces(t, module)
	require.NoError(t, module.Friends.DeleteFriendship(ctx, alice.SpaceID, bob.SpaceID))
	for _, canceler := range []string{bob.SpaceID, alice.SpaceID} {
		request, created, _, err := module.Friends.CreateFriendRequest(ctx, bob.OwnerID, bob.SpaceID, alice.SpaceID, []byte("share"), 1)
		require.NoError(t, err)
		require.True(t, created)
		items, _, err := module.Notifications.List(ctx, alice.SpaceID, "", 20)
		require.NoError(t, err)
		require.Len(t, items, 1)
		require.Equal(t, "friend_request", items[0].Kind)
		require.Equal(t, request.RequestID, items[0].FriendRequestID.Int64)
		require.False(t, items[0].PostID.Valid)
		require.True(t, items[0].Unread)
		messageUnread, err := module.Read.HasUnreadNotifications(ctx, alice.SpaceID)
		require.NoError(t, err)
		require.False(t, messageUnread)
		require.NoError(t, module.Notifications.MarkRead(ctx, bob.SpaceID, []string{items[0].NotificationID}))
		unread, err := module.Notifications.HasUnread(ctx, alice.SpaceID)
		require.NoError(t, err)
		require.True(t, unread)
		require.NoError(t, module.Notifications.MarkRead(ctx, alice.SpaceID, []string{items[0].NotificationID}))
		duplicate, created, _, err := module.Friends.CreateFriendRequest(ctx, bob.OwnerID, bob.SpaceID, alice.SpaceID, []byte("updated-share"), 1)
		require.NoError(t, err)
		require.False(t, created)
		require.Equal(t, request.RequestID, duplicate.RequestID)
		items, _, err = module.Notifications.List(ctx, alice.SpaceID, "", 20)
		require.NoError(t, err)
		require.Len(t, items, 1)
		require.False(t, items[0].Unread)
		require.NoError(t, module.Friends.DeleteFriendRequest(ctx, canceler, request.RequestID))
		items, _, err = module.Notifications.List(ctx, alice.SpaceID, "", 20)
		require.NoError(t, err)
		require.Empty(t, items)
	}
	request, _, _, err := module.Friends.CreateFriendRequest(ctx, bob.OwnerID, bob.SpaceID, alice.SpaceID, []byte("share"), 1)
	require.NoError(t, err)
	pending, _, err := module.Notifications.List(ctx, alice.SpaceID, "", 20)
	require.NoError(t, err)
	require.Len(t, pending, 1)
	_, _, err = module.Friends.ConfirmFriendRequest(ctx, alice.SpaceID, request.RequestID, []byte("share"), 1)
	require.NoError(t, err)
	items, _, err := module.Notifications.List(ctx, alice.SpaceID, "", 20)
	require.NoError(t, err)
	require.Len(t, items, 1)
	require.Equal(t, pending[0].NotificationID, items[0].NotificationID)
	require.Equal(t, "friend_accepted", items[0].Kind)
	require.Equal(t, bob.SpaceID, items[0].Actors[0].SpaceID)
	require.GreaterOrEqual(t, items[0].CreatedAt, pending[0].CreatedAt)
	require.False(t, items[0].FriendRequestID.Valid)
	require.False(t, items[0].Unread)
	accepterUnread, err := module.Notifications.HasUnread(ctx, alice.SpaceID)
	require.NoError(t, err)
	require.False(t, accepterUnread)
	items, _, err = module.Notifications.List(ctx, bob.SpaceID, "", 20)
	require.NoError(t, err)
	require.Len(t, items, 1)
	require.Equal(t, "friend_accepted", items[0].Kind)
	require.Equal(t, alice.SpaceID, items[0].Actors[0].SpaceID)
	require.False(t, items[0].FriendRequestID.Valid)
	require.True(t, items[0].Unread)
	require.Equal(t, int64(0), countSpaceRows(t, module, `SELECT COUNT(*) FROM space_messages`))
	postID, err := testCreatePost(ctx, module, bob.OwnerID, bob.SpaceID, "key", nil, 1, nil)
	require.NoError(t, err)
	require.NoError(t, testSetPostLike(ctx, module, postID, alice.SpaceID, true))
	first, cursor, err := module.Notifications.List(ctx, bob.SpaceID, "", 1)
	require.NoError(t, err)
	require.Len(t, first, 1)
	require.Equal(t, "post_like", first[0].Kind)
	require.NotEmpty(t, cursor)
	second, cursor, err := module.Notifications.List(ctx, bob.SpaceID, cursor, 1)
	require.NoError(t, err)
	require.Len(t, second, 1)
	require.Equal(t, items[0].NotificationID, second[0].NotificationID)
	require.Empty(t, cursor)
	require.NoError(t, module.Notifications.MarkRead(ctx, bob.SpaceID, []string{items[0].NotificationID}))
	unread, err := module.Notifications.HasUnread(ctx, bob.SpaceID)
	require.NoError(t, err)
	require.True(t, unread)
	require.NoError(t, module.Friends.DeleteFriendship(ctx, alice.SpaceID, bob.SpaceID))
	require.Equal(t, int64(0), countSpaceRows(t, module, `SELECT COUNT(*) FROM space_notifications WHERE kind = 'friend_accepted'`))
}

func TestReciprocalFriendRequestsKeepFriendshipNotifications(t *testing.T) {
	module := newSpaceTestModule(t)
	ctx := t.Context()
	alice, bob := notificationTestSpaces(t, module)
	require.NoError(t, module.Friends.DeleteFriendship(ctx, alice.SpaceID, bob.SpaceID))
	_, _, _, err := module.Friends.CreateFriendRequest(ctx, bob.OwnerID, bob.SpaceID, alice.SpaceID, []byte("share"), 1)
	require.NoError(t, err)
	pending, _, err := module.Notifications.List(ctx, alice.SpaceID, "", 20)
	require.NoError(t, err)
	require.Len(t, pending, 1)
	_, created, becameFriends, err := module.Friends.CreateFriendRequest(ctx, alice.OwnerID, alice.SpaceID, bob.SpaceID, []byte("share"), 1)
	require.NoError(t, err)
	require.False(t, created)
	require.True(t, becameFriends)
	items, _, err := module.Notifications.List(ctx, alice.SpaceID, "", 20)
	require.NoError(t, err)
	require.Len(t, items, 1)
	require.Equal(t, pending[0].NotificationID, items[0].NotificationID)
	require.Equal(t, "friend_accepted", items[0].Kind)
	require.Equal(t, bob.SpaceID, items[0].Actors[0].SpaceID)
	require.False(t, items[0].FriendRequestID.Valid)
	require.False(t, items[0].Unread)
	items, _, err = module.Notifications.List(ctx, bob.SpaceID, "", 20)
	require.NoError(t, err)
	require.Len(t, items, 1)
	require.Equal(t, "friend_accepted", items[0].Kind)
	require.Equal(t, alice.SpaceID, items[0].Actors[0].SpaceID)
	require.True(t, items[0].Unread)
	_, _, _, err = module.Friends.CreateFriendRequest(ctx, alice.OwnerID, alice.SpaceID, bob.SpaceID, []byte("share"), 1)
	require.ErrorIs(t, err, ErrAlreadyFriends)
	require.Equal(t, int64(2), countSpaceRows(t, module, `SELECT COUNT(*) FROM space_notifications`))
	require.Equal(t, int64(0), countSpaceRows(t, module, `SELECT COUNT(*) FROM space_friend_requests`))
}

func TestFriendAcceptanceNotificationsGroupByActor(t *testing.T) {
	module := newSpaceTestModule(t)
	ctx := t.Context()
	alice, bob := notificationTestSpaces(t, module)
	charlieID := insertSpaceUser(t, module, "charlie-notifications@example.com", "public")
	charlie, err := testCreateSpace(ctx, module, charlieID, "charlie_notifications", "root", "public", "secret", "nonce", "profile")
	require.NoError(t, err)
	require.NoError(t, testAddFriend(ctx, module, charlieID, charlie.SpaceID, alice.SpaceID, "share", 1, "share", 1))
	_, err = module.Notifications.DB.ExecContext(ctx, `
		INSERT INTO space_notifications (notification_id, recipient_space_id, actor_space_id, kind, created_at, read_at)
		VALUES ('bob-old', $1, $2, 'friend_accepted', 1000, NULL),
		       ('bob-a-latest', $1, $2, 'friend_accepted', 3000, NULL),
		       ('bob-z-latest', $1, $2, 'friend_accepted', 3000, 4000),
		       ('charlie-old', $1, $3, 'friend_accepted', 500, NULL),
		       ('charlie-latest', $1, $3, 'friend_accepted', 2000, NULL),
		       ('alice-other-recipient', $2, $1, 'friend_accepted', 3500, NULL)
	`, alice.SpaceID, bob.SpaceID, charlie.SpaceID)
	require.NoError(t, err)
	postID, err := testCreatePost(ctx, module, alice.OwnerID, alice.SpaceID, "key", nil, 1, nil)
	require.NoError(t, err)
	require.NoError(t, testSetPostLike(ctx, module, postID, bob.SpaceID, true))
	var likeID string
	require.NoError(t, module.Notifications.DB.QueryRowContext(ctx, `
		UPDATE space_notifications SET created_at = 1500 WHERE kind = 'post_like' RETURNING notification_id
	`).Scan(&likeID))

	groups := make(map[string][]string)
	cursor := ""
	for i, id := range []string{"bob-z-latest", "charlie-latest", likeID} {
		items, next, err := module.Notifications.List(ctx, alice.SpaceID, cursor, 1)
		require.NoError(t, err)
		require.Len(t, items, 1)
		require.Equal(t, id, items[0].NotificationID)
		groups[id] = items[0].NotificationIDs
		require.Equal(t, int64(1), items[0].ActorCount)
		require.Len(t, items[0].Actors, 1)
		require.True(t, items[0].Unread)
		if i < 2 {
			require.Equal(t, "friend_accepted", items[0].Kind)
			require.Equal(t, []string{bob.SpaceID, charlie.SpaceID}[i], items[0].Actors[0].SpaceID)
			require.Equal(t, []int64{3000, 2000}[i], items[0].CreatedAt)
			require.NotEmpty(t, next)
		} else {
			require.Equal(t, "post_like", items[0].Kind)
			require.Empty(t, next)
		}
		cursor = next
	}

	require.NoError(t, module.Notifications.MarkRead(ctx, bob.SpaceID, groups["bob-z-latest"]))
	require.Equal(t, int64(2), countSpaceRows(t, module, `
		SELECT COUNT(*) FROM space_notifications WHERE recipient_space_id = $1 AND actor_space_id = $2 AND kind = 'friend_accepted' AND read_at IS NULL
	`, alice.SpaceID, bob.SpaceID))
	require.NoError(t, module.Notifications.MarkRead(ctx, alice.SpaceID, groups["bob-z-latest"]))
	items, _, err := module.Notifications.List(ctx, alice.SpaceID, "", 20)
	require.NoError(t, err)
	require.Len(t, items, 3)
	require.False(t, items[0].Unread)
	require.True(t, items[1].Unread)
	require.True(t, items[2].Unread)
	require.Equal(t, int64(0), countSpaceRows(t, module, `
		SELECT COUNT(*) FROM space_notifications WHERE recipient_space_id = $1 AND actor_space_id = $2 AND kind = 'friend_accepted' AND read_at IS NULL
	`, alice.SpaceID, bob.SpaceID))
	require.NoError(t, module.Notifications.MarkRead(ctx, alice.SpaceID, append(groups["charlie-latest"], likeID)))
	unread, err := module.Notifications.HasUnread(ctx, alice.SpaceID)
	require.NoError(t, err)
	require.False(t, unread)
	unread, err = module.Notifications.HasUnread(ctx, bob.SpaceID)
	require.NoError(t, err)
	require.True(t, unread)

	_, err = module.Notifications.DB.ExecContext(ctx, `
		INSERT INTO space_notifications (notification_id, recipient_space_id, actor_space_id, kind, created_at)
		VALUES ('bob-new', $1, $2, 'friend_accepted', 5000)
	`, alice.SpaceID, bob.SpaceID)
	require.NoError(t, err)
	require.NoError(t, module.Notifications.MarkRead(ctx, alice.SpaceID, groups["bob-z-latest"]))
	items, _, err = module.Notifications.List(ctx, alice.SpaceID, "", 20)
	require.NoError(t, err)
	require.Len(t, items, 3)
	require.Equal(t, "bob-new", items[0].NotificationID)
	require.True(t, items[0].Unread)
	require.NoError(t, module.Notifications.MarkRead(ctx, alice.SpaceID, []string{"bob-new"}))
	unread, err = module.Notifications.HasUnread(ctx, alice.SpaceID)
	require.NoError(t, err)
	require.False(t, unread)
}

func TestFriendNotificationsMigrationPreservesRequestsAndAcceptanceReadState(t *testing.T) {
	module := newSpaceTestModule(t)
	ctx := t.Context()
	alice, bob := notificationTestSpaces(t, module)
	postID, err := testCreatePost(ctx, module, alice.OwnerID, alice.SpaceID, "key", nil, 1, nil)
	require.NoError(t, err)
	require.NoError(t, testSetPostLike(ctx, module, postID, bob.SpaceID, true))
	up, err := os.ReadFile("migrations/150_space_notifications.up.sql")
	require.NoError(t, err)
	down, err := os.ReadFile("migrations/150_space_notifications.down.sql")
	require.NoError(t, err)
	tx, err := module.Notifications.DB.BeginTx(ctx, nil)
	require.NoError(t, err)
	defer tx.Rollback()
	_, err = tx.ExecContext(ctx, string(down))
	require.NoError(t, err)
	var requestID int64
	require.NoError(t, tx.QueryRowContext(ctx, `INSERT INTO space_friend_requests (requester_space_id, target_space_id, requester_friend_sealed_space_key, created_at) VALUES ($1, $2, $3, 1000) RETURNING request_id`, bob.SpaceID, alice.SpaceID, []byte("share")).Scan(&requestID))
	_, err = tx.ExecContext(ctx, `INSERT INTO space_messages (message_id, sender_space_id, recipient_space_id, kind, created_at) VALUES ('read-acceptance', $1, $2, 'friend_added', 1000), ('unread-acceptance', $1, $2, 'friend_added', 3000)`, alice.SpaceID, bob.SpaceID)
	require.NoError(t, err)
	_, err = tx.ExecContext(ctx, `UPDATE space_notification_read_markers SET read_at = 2000 WHERE viewer_space_id = $1 AND friend_space_id = $2`, bob.SpaceID, alice.SpaceID)
	require.NoError(t, err)
	_, err = tx.ExecContext(ctx, string(up))
	require.NoError(t, err)
	var readAt sql.NullInt64
	require.NoError(t, tx.QueryRowContext(ctx, `SELECT read_at FROM space_notifications WHERE notification_id = 'read-acceptance'`).Scan(&readAt))
	require.Equal(t, sql.NullInt64{Int64: 2000, Valid: true}, readAt)
	require.NoError(t, tx.QueryRowContext(ctx, `SELECT read_at FROM space_notifications WHERE notification_id = 'unread-acceptance'`).Scan(&readAt))
	require.False(t, readAt.Valid)
	require.NoError(t, tx.QueryRowContext(ctx, `SELECT read_at FROM space_notifications WHERE friend_request_id = $1`, requestID).Scan(&readAt))
	require.False(t, readAt.Valid)
	var count int
	require.NoError(t, tx.QueryRowContext(ctx, `SELECT COUNT(*) FROM space_notifications WHERE kind = 'post_like'`).Scan(&count))
	require.Equal(t, 1, count)
	require.NoError(t, tx.QueryRowContext(ctx, `SELECT COUNT(*) FROM space_messages`).Scan(&count))
	require.Zero(t, count)
	_, err = tx.ExecContext(ctx, `DELETE FROM space_friend_requests WHERE request_id = $1`, requestID)
	require.NoError(t, err)
	require.NoError(t, tx.QueryRowContext(ctx, `SELECT COUNT(*) FROM space_notifications WHERE kind = 'friend_request'`).Scan(&count))
	require.Zero(t, count)
	_, err = tx.ExecContext(ctx, string(down))
	require.NoError(t, err)
	require.NoError(t, tx.QueryRowContext(ctx, `SELECT COUNT(*) FROM space_messages WHERE kind = 'friend_added'`).Scan(&count))
	require.Equal(t, 2, count)
}
