[package]
name = "ente-auth"
edition.workspace = true

[dependencies]
ente-core.workspace = true
serde.workspace = true
serde_json = { workspace = true, features = ["raw_value"] }
thiserror.workspace = true
url.workspace = true
uuid = { workspace = true, features = ["serde"] }
zeroize.workspace = true

[lints]
workspace = true
